---

- name: guess pulseaudio_mode
  block:
    - name: set pulseaudio_mode to server
      set_fact:
        pulseaudio_mode: server
      when: (hosttype|d('')) in ['server']

    - name: set pulseaudio_mode to user
      set_fact:
        pulseaudio_mode: user
      when: (hosttype|d('')) in ['desktop']

  when: pulseaudio_mode is not defined


- name: prepare pulseaudio configuration
  block:
    - name: prepare server settings
      set_fact:
        pulseaudio_client_conf_entries: "{{ pulseaudio_server_client_conf_entries }}"
        pulseaudio_daemon_conf_entries: "{{ pulseaudio_server_daemon_conf_entries }}"
        pulseaudio_service_to_deploy: "{{ pulseaudio_server_service }}"
      when: pulseaudio_mode == "server"

    - name: prepare user settings
      set_fact:
        pulseaudio_client_conf_entries: "{{ pulseaudio_user_client_conf_entries }}"
        pulseaudio_daemon_conf_entries: "{{ pulseaudio_user_daemon_conf_entries }}"
        pulseaudio_service_to_deploy:
        pulseaudio_default_service_to_enable:
        pulseaudio_default_services_to_disable:
          - "{{ pulseaudio_server_service|d(omit) }}"
          - "{{ pulseaudio_user_service|d(omit) }}"
      when: pulseaudio_mode == "user"

    - name: prepare server services for system
      set_fact:
        pulseaudio_service_to_enable: "{{ pulseaudio_server_service|d(omit) }}"
        pulseaudio_services_to_disable:
          - "{{ pulseaudio_user_service|d(omit) }}"
      when:
        - pulseaudio_mode == "server"
        - not has_daemontools

    - name: prepare server services for daemontools
      set_fact:
        pulseaudio_service_to_enable:
        pulseaudio_services_to_disable:
          - "{{ pulseaudio_server_service|d(omit) }}"
          - "{{ pulseaudio_user_service|d(omit) }}"
      when:
        - pulseaudio_mode == "server"
        - has_daemontools


- name: configure default pulseaudio
  block:
    - name: setup client.conf
      lineinfile:
        path: "{{ pulseaudio_client_conf }}"
        regexp: '^{{ item.key }} ='
        line: "{{ item.key }} = {{ item.value }}"
      loop: "{{ pulseaudio_client_conf_entries }}"
      register: t_pulseaudio_client_conf

    - name: setup daemon.conf
      lineinfile:
        path: "{{ pulseaudio_daemon_conf }}"
        regexp: '^{{ item.key }} ='
        line: "{{ item.key }} = {{ item.value }}"
      loop: "{{ pulseaudio_daemon_conf_entries }}"
      register: t_pulseaudio_daemon_conf

    - name: disable alternate systemd pulseaudio service
      service:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop: "{{ pulseaudio_services_to_disable|d([]) }}"
      when:
        - ansible_service_mgr == "systemd"

    - name: setup systemd pulseaudio service
      block:
        - name: deploy pulseaudio service
          template:
            src: "pulseaudio/systemd/{{ pulseaudio_service_to_deploy }}"
            dest: "{{ systemd_service_lib}}/{{ pulseaudio_service_to_deploy }}"
            owner: root
            group: root
            mode: "0644"
          register: t_pulseaudio_service
          when: (pulseaudio_service_to_deploy|d('')) != ''

        - name: start service
          service:
            name: "{{ pulseaudio_service_to_enable }}"
            enabled: yes
            state: started
          when: (pulseaudio_service_to_enable|d('')) != ''

        - name: restart service
          service:
            name: "{{ pulseaudio_service_to_enable }}"
            enabled: yes
            state: restarted
          when:
            - (pulseaudio_service_to_enable|d('')) != ''
            - t_pulseaudio_client_conf.changed or t_pulseaudio_daemon_conf.changed or t_pulseaudio_service.changed

      when:
        - ansible_service_mgr == "systemd"
        - not (has_daemontools|d(false))

    - name: setup daemontools pulseaudio service
      block:
        - name: create daemontools workspaces
          file:
            path: "{{ pulseaudio_daemontools_dir }}/{{ item.path }}"
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            mode: "{{ item.mode }}"
            state: directory
          loop: "{{ daemontools_directories_template }}"

        - name: deploy daemontools run scripts
          template:
            src: "svscan/{{ item.path }}"
            dest: "{{ pulseaudio_daemontools_dir }}/{{ item.path }}"
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            mode: "{{ item.mode }}"
          loop: "{{ daemontools_scripts_template }}"

        - name: supervise (link) daemontools services
          file:
            src: "{{ pulseaudio_daemontools_dir }}"
            dest: "{{ daemontools_svscan_dir }}/pulseaudio"
            state: link

      when:
        - has_daemontools|d(false)
        - (pulseaudio_service_to_enable|d('')) != ''

  when: pulseaudio_mode in ['server', 'user']
